version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: paysera_assignment_php
    volumes:
      - ./backend-api:/var/www/html
    depends_on:
      - mysql
      - redis
      - rabbitmq

  nginx:
    image: nginx:alpine
    container_name: paysera_assignment_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend-api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: paysera_assignment_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paysera-assignment
      MYSQL_USER: paysera
      MYSQL_PASSWORD: paysera
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: paysera_assignment_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: paysera_assignment_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: paysera
      RABBITMQ_DEFAULT_PASS: paysera
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data: