framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                    queues:
                        async:
                            binding_keys: [async]
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 60000
            sync: 'sync://'

        routing:
            'App\Message\TransactionSucceededMessage': async

when@test:
    framework:
        messenger:
            routing:
                'App\Message\TransactionSucceededMessage': sync
